version: '3.8'

services:
  service:
    build:
      context: .
    ports:
      - "8081:8081"
    env_file: .env
    restart: on-failure
    depends_on:
      - postgres


  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    restart: on-failure

